### ISSUE TITLE
Checkpoint functionality does not work

### ISSUE THREAD

**Issue by IcanDXD** [byungheon-jeong/google-eartheingine-labeler#3]
The checkpoint functionality is not working as intended. Skipping creates a bug where the program, when relaunched, does not start you on the last image you labeled but instead the first image you skipped.

**Comment by byungheon-jeong** [comment]
Solved via https://github.com/byungheon-jeong/google-eartheingine-labeler/commit/3f7584d425ec9a289e31cddc72de4cd77e0f4d87
